GET http://localhost:3000/botVerify12
###

GET http://localhost:3000/userConformation/?username=surya&password=123456789


###

POST http://localhost:3000/users/
Content-Type: application/json

{
  "username1": "rahul",
  "password1": "rahul@1986"
}

###

GET http://localhost:3000/storeNwtchat/?chatlog=1234

###

GET http://localhost:3000/blockchainpart

###
GET http://localhost:3000/kycdetails

###
GET http://localhost:3000/storeKYC/?kyclog=0 100 100

###
GET http://localhost:3000/transactiondetails

###
GET http://localhost:3000/storeTD/?translog=kjgsadfkjasdklajhdaslkdasdklasdlka  

###
GET http://localhost:3000/p  


