GET http://localhost:3000/

###

GET http://localhost:3000/userConformation/?username=surya&password=123456789


###

POST http://localhost:3000/users/
Content-Type: application/json

{
  "username": "satish",
  "password": "9966160639"
}

###
